	virtual Point2i screen_get_position(int p_screen = SCREEN_OF_MAIN_WINDOW) const override;
	virtual Size2i screen_get_size(int p_screen = SCREEN_OF_MAIN_WINDOW) const override;
	virtual Rect2i screen_get_usable_rect(int p_screen = SCREEN_OF_MAIN_WINDOW) const override;
	virtual int screen_get_dpi(int p_screen = SCREEN_OF_MAIN_WINDOW) const override;
	virtual float screen_get_refresh_rate(int p_screen = SCREEN_OF_MAIN_WINDOW) const override;
	virtual void window_set_transient(WindowID p_window, WindowID p_parent) override;
	virtual void window_set_max_size(const Size2i p_size, WindowID p_window = MAIN_WINDOW_ID) override;
	virtual Size2i window_get_max_size(WindowID p_window = MAIN_WINDOW_ID) const override;
	virtual void window_set_min_size(const Size2i p_size, WindowID p_window = MAIN_WINDOW_ID) override;
	virtual Size2i window_get_min_size(WindowID p_window = MAIN_WINDOW_ID) const override;
	virtual bool window_is_maximize_allowed(WindowID p_window = MAIN_WINDOW_ID) const override;
	virtual void window_request_attention(WindowID p_window = MAIN_WINDOW_ID) override;
	virtual void window_move_to_foreground(WindowID p_window = MAIN_WINDOW_ID) override;
	virtual bool window_is_focused(WindowID p_window = MAIN_WINDOW_ID) const override;
	virtual bool window_can_draw(WindowID p_window = MAIN_WINDOW_ID) const override;
	virtual Error init() override;
	virtual bool window_create(DisplayServer::WindowID p_window_id, void *p_handle) override;
	virtual void window_destroy(DisplayServer::WindowID p_window_id) override;
	virtual RID accessibility_create_element(DisplayServer::WindowID p_window_id, DisplayServer::AccessibilityRole p_role) override;
	virtual RID accessibility_create_sub_element(const RID &p_parent_rid, DisplayServer::AccessibilityRole p_role, int p_insert_pos = -1) override;
	virtual RID accessibility_create_sub_text_edit_elements(const RID &p_parent_rid, const RID &p_shaped_text, float p_min_height, int p_insert_pos = -1) override;
	virtual bool accessibility_has_element(const RID &p_id) const override;
	virtual void accessibility_free_element(const RID &p_id) override;
	virtual void accessibility_element_set_meta(const RID &p_id, const Variant &p_meta) override;
	virtual Variant accessibility_element_get_meta(const RID &p_id) const override;
	virtual void accessibility_update_if_active(const Callable &p_callable) override;
	virtual RID accessibility_get_window_root(DisplayServer::WindowID p_window_id) const override;
	virtual void accessibility_update_set_focus(const RID &p_id) override;
	virtual void accessibility_set_window_rect(DisplayServer::WindowID p_window_id, const Rect2 &p_rect_out, const Rect2 &p_rect_in) override;
	virtual void accessibility_set_window_focused(DisplayServer::WindowID p_window_id, bool p_focused) override;
	virtual void accessibility_update_set_role(const RID &p_id, DisplayServer::AccessibilityRole p_role) override;
	virtual void accessibility_update_set_name(const RID &p_id, const String &p_name) override;
	virtual void accessibility_update_set_extra_info(const RID &p_id, const String &p_name_extra_info) override;
	virtual void accessibility_update_set_description(const RID &p_id, const String &p_description) override;
	virtual void accessibility_update_set_value(const RID &p_id, const String &p_value) override;
	virtual void accessibility_update_set_tooltip(const RID &p_id, const String &p_tooltip) override;
	virtual void accessibility_update_set_bounds(const RID &p_id, const Rect2 &p_rect) override;
	virtual void accessibility_update_set_transform(const RID &p_id, const Transform2D &p_transform) override;
	virtual void accessibility_update_add_child(const RID &p_id, const RID &p_child_id) override;
	virtual void accessibility_update_add_related_controls(const RID &p_id, const RID &p_related_id) override;
	virtual void accessibility_update_add_related_details(const RID &p_id, const RID &p_related_id) override;
	virtual void accessibility_update_add_related_described_by(const RID &p_id, const RID &p_related_id) override;
	virtual void accessibility_update_add_related_flow_to(const RID &p_id, const RID &p_related_id) override;
	virtual void accessibility_update_add_related_labeled_by(const RID &p_id, const RID &p_related_id) override;
	virtual void accessibility_update_add_related_radio_group(const RID &p_id, const RID &p_related_id) override;
	virtual void accessibility_update_set_active_descendant(const RID &p_id, const RID &p_other_id) override;
	virtual void accessibility_update_set_next_on_line(const RID &p_id, const RID &p_other_id) override;
	virtual void accessibility_update_set_previous_on_line(const RID &p_id, const RID &p_other_id) override;
	virtual void accessibility_update_set_member_of(const RID &p_id, const RID &p_group_id) override;
	virtual void accessibility_update_set_in_page_link_target(const RID &p_id, const RID &p_other_id) override;
	virtual void accessibility_update_set_error_message(const RID &p_id, const RID &p_other_id) override;
	virtual void accessibility_update_set_live(const RID &p_id, DisplayServer::AccessibilityLiveMode p_live) override;
	virtual void accessibility_update_add_action(const RID &p_id, DisplayServer::AccessibilityAction p_action, const Callable &p_callable) override;
	virtual void accessibility_update_add_custom_action(const RID &p_id, int p_action_id, const String &p_action_description) override;
	virtual void accessibility_update_set_table_row_count(const RID &p_id, int p_count) override;
	virtual void accessibility_update_set_table_column_count(const RID &p_id, int p_count) override;
	virtual void accessibility_update_set_table_row_index(const RID &p_id, int p_index) override;
	virtual void accessibility_update_set_table_column_index(const RID &p_id, int p_index) override;
	virtual void accessibility_update_set_table_cell_position(const RID &p_id, int p_row_index, int p_column_index) override;
	virtual void accessibility_update_set_table_cell_span(const RID &p_id, int p_row_span, int p_column_span) override;
	virtual void accessibility_update_set_list_item_count(const RID &p_id, int p_size) override;
	virtual void accessibility_update_set_list_item_index(const RID &p_id, int p_index) override;
	virtual void accessibility_update_set_list_item_level(const RID &p_id, int p_level) override;
	virtual void accessibility_update_set_list_item_selected(const RID &p_id, bool p_selected) override;
	virtual void accessibility_update_set_list_item_expanded(const RID &p_id, bool p_expanded) override;
	virtual void accessibility_update_set_popup_type(const RID &p_id, DisplayServer::AccessibilityPopupType p_popup) override;
	virtual void accessibility_update_set_checked(const RID &p_id, bool p_checekd) override;
	virtual void accessibility_update_set_num_value(const RID &p_id, double p_position) override;
	virtual void accessibility_update_set_num_range(const RID &p_id, double p_min, double p_max) override;
	virtual void accessibility_update_set_num_step(const RID &p_id, double p_step) override;
	virtual void accessibility_update_set_num_jump(const RID &p_id, double p_jump) override;
	virtual void accessibility_update_set_scroll_x(const RID &p_id, double p_position) override;
	virtual void accessibility_update_set_scroll_x_range(const RID &p_id, double p_min, double p_max) override;
	virtual void accessibility_update_set_scroll_y(const RID &p_id, double p_position) override;
	virtual void accessibility_update_set_scroll_y_range(const RID &p_id, double p_min, double p_max) override;
	virtual void accessibility_update_set_text_decorations(const RID &p_id, bool p_underline, bool p_strikethrough, bool p_overline) override;
	virtual void accessibility_update_set_text_align(const RID &p_id, HorizontalAlignment p_align) override;
	virtual void accessibility_update_set_text_selection(const RID &p_id, const RID &p_text_start_id, int p_start_char, const RID &p_text_end_id, int p_end_char) override;
	virtual void accessibility_update_set_flag(const RID &p_id, DisplayServer::AccessibilityFlags p_flag, bool p_value) override;
	virtual void accessibility_update_set_classname(const RID &p_id, const String &p_classname) override;
	virtual void accessibility_update_set_placeholder(const RID &p_id, const String &p_placeholder) override;
	virtual void accessibility_update_set_language(const RID &p_id, const String &p_language) override;
	virtual void accessibility_update_set_text_orientation(const RID &p_id, bool p_vertical) override;
	virtual void accessibility_update_set_list_orientation(const RID &p_id, bool p_vertical) override;
	virtual void accessibility_update_set_shortcut(const RID &p_id, const String &p_shortcut) override;
	virtual void accessibility_update_set_url(const RID &p_id, const String &p_url) override;
	virtual void accessibility_update_set_role_description(const RID &p_id, const String &p_description) override;
	virtual void accessibility_update_set_state_description(const RID &p_id, const String &p_description) override;
	virtual void accessibility_update_set_color_value(const RID &p_id, const Color &p_color) override;
	virtual void accessibility_update_set_background_color(const RID &p_id, const Color &p_color) override;
	virtual void accessibility_update_set_foreground_color(const RID &p_id, const Color &p_color) override;

