#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")

source_files = [
    "display_server_sdl2.cpp",
]

objects = []
for source_file in source_files:
    objects.append(env.Object(source_file))

Return("objects")
