/**************************************************************************/
/*  steam_stub.cpp                                                        */
/**************************************************************************/
#include "steam_stub.h"

#include "core/object/class_db.h"
#include "core/variant/dictionary.h"
#include "core/variant/variant.h"

namespace {

void bind_stub_method(const char *p_name) {
    MethodInfo method_info;
    method_info.name = p_name;
    ClassDB::bind_vararg_method(METHOD_FLAGS_DEFAULT, p_name, &Steam::stub_call, method_info);
}

} // namespace

Variant Steam::stub_call(const Variant **p_args, int p_arg_count, Callable::CallError &r_error) {
    (void)p_args;
    (void)p_arg_count;
    r_error.error = Callable::CallError::CALL_OK;
    return Variant();
}

Dictionary Steam::steamInitEx(int p_app_id, bool p_embed_callbacks) {
    (void)p_app_id;
    (void)p_embed_callbacks;
    Dictionary result;
    result["status"] = 1; // k_ESteamAPIInitResult_OK
    result["verbal"] = "Steam connected (PortMaster offline mode)";
    return result;
}

bool Steam::steamInit(bool p_embed_callbacks) {
    (void)p_embed_callbacks;
    return true;
}

void Steam::run_callbacks() {}

void Steam::runCallbacks() {}

bool Steam::isSteamRunning() {
    return true;
}

bool Steam::loggedOn() {
    return true;
}

uint64_t Steam::getSteamID() {
    return 76561198000000001ULL;
}

String Steam::getPersonaName() {
    return "Player";
}

void Steam::_bind_methods() {
    ClassDB::bind_method(D_METHOD("steamInitEx", "app_id", "embed_callbacks"), &Steam::steamInitEx, DEFVAL(0), DEFVAL(false));
    ClassDB::bind_method(D_METHOD("steamInit", "embed_callbacks"), &Steam::steamInit, DEFVAL(false));
    ClassDB::bind_method(D_METHOD("run_callbacks"), &Steam::run_callbacks);
    ClassDB::bind_method(D_METHOD("runCallbacks"), &Steam::runCallbacks);
    ClassDB::bind_method(D_METHOD("isSteamRunning"), &Steam::isSteamRunning);
    ClassDB::bind_method(D_METHOD("loggedOn"), &Steam::loggedOn);
    ClassDB::bind_method(D_METHOD("getSteamID"), &Steam::getSteamID);
    ClassDB::bind_method(D_METHOD("getPersonaName"), &Steam::getPersonaName);

    // Auto-generated stubs for all other GodotSteam methods
    bind_stub_method("acceptConnection");
    bind_stub_method("acceptGame");
    bind_stub_method("acceptP2PSessionWithUser");
    bind_stub_method("acceptSessionWithUser");
    bind_stub_method("activateActionSet");
    bind_stub_method("activateActionSetLayer");
    bind_stub_method("activateGameOverlay");
    bind_stub_method("activateGameOverlayInviteDialog");
    bind_stub_method("activateGameOverlayInviteDialogConnectString");
    bind_stub_method("activateGameOverlayToStore");
    bind_stub_method("activateGameOverlayToUser");
    bind_stub_method("activateGameOverlayToWebPage");
    bind_stub_method("activationSuccess");
    bind_stub_method("addAppDependency");
    bind_stub_method("addContentDescriptor");
    bind_stub_method("addDependency");
    bind_stub_method("addExcludedTag");
    bind_stub_method("addFavoriteGame");
    bind_stub_method("addGamePhaseTag");
    bind_stub_method("addGameSearchParams");
    bind_stub_method("addHeader");
    bind_stub_method("addInstantaneousTimelineEvent");
    bind_stub_method("addItemKeyValueTag");
    bind_stub_method("addItemPreviewFile");
    bind_stub_method("addItemPreviewVideo");
    bind_stub_method("addItemToFavorites");
    bind_stub_method("addPromoItem");
    bind_stub_method("addPromoItems");
    bind_stub_method("addRangeTimelineEvent");
    bind_stub_method("addRequestLobbyListDistanceFilter");
    bind_stub_method("addRequestLobbyListFilterSlotsAvailable");
    bind_stub_method("addRequestLobbyListNearValueFilter");
    bind_stub_method("addRequestLobbyListNumericalFilter");
    bind_stub_method("addRequestLobbyListResultCountFilter");
    bind_stub_method("addRequestLobbyListStringFilter");
    bind_stub_method("addRequiredKeyValueTag");
    bind_stub_method("addRequiredTag");
    bind_stub_method("addRequiredTagGroup");
    bind_stub_method("addScreenshotToLibrary");
    bind_stub_method("addVRScreenshotToLibrary");
    bind_stub_method("advertiseGame");
    bind_stub_method("allowP2PPacketRelay");
    bind_stub_method("allowStartRequest");
    bind_stub_method("attachLeaderboardUGC");
    bind_stub_method("beginAsyncRequestFakeIP");
    bind_stub_method("beginAuthSession");
    bind_stub_method("beginFileWriteBatch");
    bind_stub_method("cancelAuthTicket");
    bind_stub_method("cancelQuery");
    bind_stub_method("cancelRequestPlayersForGame");
    bind_stub_method("cancelReservation");
    bind_stub_method("cancelServerQuery");
    bind_stub_method("changeNumOpenSlots");
    bind_stub_method("checkFileSignature");
    bind_stub_method("checkPingDataUpToDate");
    bind_stub_method("checkResultSteamID");
    bind_stub_method("clearAchievement");
    bind_stub_method("clearRichPresence");
    bind_stub_method("clearTimelineTooltip");
    bind_stub_method("closeChannelWithUser");
    bind_stub_method("closeClanChatWindowInSteam");
    bind_stub_method("closeConnection");
    bind_stub_method("closeListenSocket");
    bind_stub_method("closeP2PChannelWithUser");
    bind_stub_method("closeP2PSessionWithUser");
    bind_stub_method("closeSessionWithUser");
    bind_stub_method("configureConnectionLanes");
    bind_stub_method("connectByIPAddress");
    bind_stub_method("connectP2P");
    bind_stub_method("connectToHostedDedicatedServer");
    bind_stub_method("consumeItem");
    bind_stub_method("convertPingLocationToString");
    bind_stub_method("copyToClipboard");
    bind_stub_method("createBeacon");
    bind_stub_method("createBrowser");
    bind_stub_method("createCookieContainer");
    bind_stub_method("createFakeUDPPort");
    bind_stub_method("createHTTPRequest");
    bind_stub_method("createHostedDedicatedServerListenSocket");
    bind_stub_method("createItem");
    bind_stub_method("createListenSocketIP");
    bind_stub_method("createListenSocketP2P");
    bind_stub_method("createListenSocketP2PFakeIP");
    bind_stub_method("createLobby");
    bind_stub_method("createPollGroup");
    bind_stub_method("createQueryAllUGCRequest");
    bind_stub_method("createQueryUGCDetailsRequest");
    bind_stub_method("createQueryUserUGCRequest");
    bind_stub_method("createSocketPair");
    bind_stub_method("currentEntryDidChange");
    bind_stub_method("currentEntryIsAvailable");
    bind_stub_method("currentEntryWillChange");
    bind_stub_method("deactivateActionSetLayer");
    bind_stub_method("deactivateAllActionSetLayers");
    bind_stub_method("declineGame");
    bind_stub_method("decompressVoice");
    bind_stub_method("deferHTTPRequest");
    bind_stub_method("deleteItem");
    bind_stub_method("deleteLobbyData");
    bind_stub_method("deregisterSteamMusicRemote");
    bind_stub_method("deserializeResult");
    bind_stub_method("destroyBeacon");
    bind_stub_method("destroyPollGroup");
    bind_stub_method("destroyResult");
    bind_stub_method("disableRemotePlayTogetherDirectInput");
    bind_stub_method("dismissFloatingGamepadTextInput");
    bind_stub_method("dismissGamepadTextInput");
    bind_stub_method("doesEventRecordingExist");
    bind_stub_method("doesGamePhaseRecordingExist");
    bind_stub_method("downloadClanActivityCounts");
    bind_stub_method("downloadItem");
    bind_stub_method("downloadLeaderboardEntries");
    bind_stub_method("downloadLeaderboardEntriesForUsers");
    bind_stub_method("enableActionEventCallbacks");
    bind_stub_method("enableDeviceCallbacks");
    bind_stub_method("enableLooped");
    bind_stub_method("enablePlayNext");
    bind_stub_method("enablePlayPrevious");
    bind_stub_method("enablePlaylists");
    bind_stub_method("enableQueue");
    bind_stub_method("enableRemotePlayTogetherDirectInput");
    bind_stub_method("enableShuffled");
    bind_stub_method("endAuthSession");
    bind_stub_method("endFileWriteBatch");
    bind_stub_method("endGame");
    bind_stub_method("endGamePhase");
    bind_stub_method("endGameSearch");
    bind_stub_method("endRangeTimelineEvent");
    bind_stub_method("enumerateFollowingList");
    bind_stub_method("estimatePingTimeBetweenTwoLocations");
    bind_stub_method("estimatePingTimeFromLocalHost");
    bind_stub_method("exchangeItems");
    bind_stub_method("executeJavascript");
    bind_stub_method("fileDelete");
    bind_stub_method("fileExists");
    bind_stub_method("fileForget");
    bind_stub_method("filePersisted");
    bind_stub_method("fileRead");
    bind_stub_method("fileReadAsync");
    bind_stub_method("fileShare");
    bind_stub_method("fileWrite");
    bind_stub_method("fileWriteAsync");
    bind_stub_method("fileWriteStreamCancel");
    bind_stub_method("fileWriteStreamClose");
    bind_stub_method("fileWriteStreamOpen");
    bind_stub_method("fileWriteStreamWriteChunk");
    bind_stub_method("filterText");
    bind_stub_method("find");
    bind_stub_method("findLeaderboard");
    bind_stub_method("findOrCreateLeaderboard");
    bind_stub_method("flushMessagesOnConnection");
    bind_stub_method("generateItems");
    bind_stub_method("getAPICallFailureReason");
    bind_stub_method("getAchievement");
    bind_stub_method("getAchievementAchievedPercent");
    bind_stub_method("getAchievementAndUnlockTime");
    bind_stub_method("getAchievementDisplayAttribute");
    bind_stub_method("getAchievementIcon");
    bind_stub_method("getAchievementName");
    bind_stub_method("getAchievementProgressLimitsFloat");
    bind_stub_method("getAchievementProgressLimitsInt");
    bind_stub_method("getActionOriginFromXboxOrigin");
    bind_stub_method("getActionSetHandle");
    bind_stub_method("getActiveActionSetLayers");
    bind_stub_method("getAllItems");
    bind_stub_method("getAllLobbyData");
    bind_stub_method("getAnalogActionData");
    bind_stub_method("getAnalogActionHandle");
    bind_stub_method("getAnalogActionOrigins");
    bind_stub_method("getAppBuildId");
    bind_stub_method("getAppDependencies");
    bind_stub_method("getAppID");
    bind_stub_method("getAppInstallDir");
    bind_stub_method("getAppOwner");
    bind_stub_method("getAuthSessionTicket");
    bind_stub_method("getAuthTicketForWebApi");
    bind_stub_method("getAuthenticationStatus");
    bind_stub_method("getAvailableBeaconLocations");
    bind_stub_method("getAvailableGameLanguages");
    bind_stub_method("getAvailableP2PPacketSize");
    bind_stub_method("getAvailableVoice");
    bind_stub_method("getBeaconByIndex");
    bind_stub_method("getBeaconDetails");
    bind_stub_method("getBeaconLocationData");
    bind_stub_method("getBetaInfo");
    bind_stub_method("getCachedUGCCount");
    bind_stub_method("getCachedUGCHandle");
    bind_stub_method("getCertificateRequest");
    bind_stub_method("getChatMemberByIndex");
    bind_stub_method("getClanActivityCounts");
    bind_stub_method("getClanByIndex");
    bind_stub_method("getClanChatMemberCount");
    bind_stub_method("getClanChatMessage");
    bind_stub_method("getClanCount");
    bind_stub_method("getClanName");
    bind_stub_method("getClanOfficerByIndex");
    bind_stub_method("getClanOfficerCount");
    bind_stub_method("getClanOwner");
    bind_stub_method("getClanTag");
    bind_stub_method("getConfigValue");
    bind_stub_method("getConfigValueInfo");
    bind_stub_method("getConnectedControllers");
    bind_stub_method("getConnectedUniverse");
    bind_stub_method("getConnectionInfo");
    bind_stub_method("getConnectionName");
    bind_stub_method("getConnectionRealTimeStatus");
    bind_stub_method("getConnectionUserData");
    bind_stub_method("getControllerForGamepadIndex");
    bind_stub_method("getCoplayFriend");
    bind_stub_method("getCoplayFriendCount");
    bind_stub_method("getCurrentActionSet");
    bind_stub_method("getCurrentBatteryPower");
    bind_stub_method("getCurrentBetaName");
    bind_stub_method("getCurrentGameLanguage");
    bind_stub_method("getDLCCount");
    bind_stub_method("getDLCData");
    bind_stub_method("getDLCDataByIndex");
    bind_stub_method("getDLCDownloadProgress");
    bind_stub_method("getDetailedConnectionStatus");
    bind_stub_method("getDeviceBindingRevision");
    bind_stub_method("getDigitalActionData");
    bind_stub_method("getDigitalActionHandle");
    bind_stub_method("getDigitalActionOrigins");
    bind_stub_method("getDirectPingToPOP");
    bind_stub_method("getDurationControl");
    bind_stub_method("getEarliestPurchaseUnixTime");
    bind_stub_method("getEncryptedAppTicket");
    bind_stub_method("getFakeIP");
    bind_stub_method("getFavoriteGames");
    bind_stub_method("getFileCount");
    bind_stub_method("getFileDetails");
    bind_stub_method("getFileNameAndSize");
    bind_stub_method("getFileSize");
    bind_stub_method("getFileTimestamp");
    bind_stub_method("getFollowerCount");
    bind_stub_method("getFriendByIndex");
    bind_stub_method("getFriendCoplayGame");
    bind_stub_method("getFriendCoplayTime");
    bind_stub_method("getFriendCount");
    bind_stub_method("getFriendCountFromSource");
    bind_stub_method("getFriendFromSourceByIndex");
    bind_stub_method("getFriendGamePlayed");
    bind_stub_method("getFriendMessage");
    bind_stub_method("getFriendPersonaName");
    bind_stub_method("getFriendPersonaNameHistory");
    bind_stub_method("getFriendPersonaState");
    bind_stub_method("getFriendRelationship");
    bind_stub_method("getFriendRichPresence");
    bind_stub_method("getFriendRichPresenceKeyByIndex");
    bind_stub_method("getFriendRichPresenceKeyCount");
    bind_stub_method("getFriendSteamLevel");
    bind_stub_method("getFriendsGroupCount");
    bind_stub_method("getFriendsGroupIDByIndex");
    bind_stub_method("getFriendsGroupMembersCount");
    bind_stub_method("getFriendsGroupMembersList");
    bind_stub_method("getFriendsGroupName");
    bind_stub_method("getGameBadgeLevel");
    bind_stub_method("getGamepadIndexForController");
    bind_stub_method("getGlobalStatFloat");
    bind_stub_method("getGlobalStatFloatHistory");
    bind_stub_method("getGlobalStatInt");
    bind_stub_method("getGlobalStatIntHistory");
    bind_stub_method("getGlyphForActionOrigin");
    bind_stub_method("getGlyphForXboxOrigin");
    bind_stub_method("getGlyphPNGForActionOrigin");
    bind_stub_method("getGlyphSVGForActionOrigin");
    bind_stub_method("getHTTPDownloadProgressPct");
    bind_stub_method("getHTTPRequestWasTimedOut");
    bind_stub_method("getHTTPResponseBodyData");
    bind_stub_method("getHTTPResponseBodySize");
    bind_stub_method("getHTTPResponseHeaderSize");
    bind_stub_method("getHTTPResponseHeaderValue");
    bind_stub_method("getHTTPStreamingResponseBodyData");
    bind_stub_method("getHostedDedicatedServerPOPId");
    bind_stub_method("getHostedDedicatedServerPort");
    bind_stub_method("getIPCCallCount");
    bind_stub_method("getIPCountry");
    bind_stub_method("getIPv6ConnectivityState");
    bind_stub_method("getImageRGBA");
    bind_stub_method("getImageSize");
    bind_stub_method("getInput");
    bind_stub_method("getInputTypeForHandle");
    bind_stub_method("getInstalledDepots");
    bind_stub_method("getItemDefinitionProperty");
    bind_stub_method("getItemDownloadInfo");
    bind_stub_method("getItemInstallInfo");
    bind_stub_method("getItemPrice");
    bind_stub_method("getItemState");
    bind_stub_method("getItemUpdateProgress");
    bind_stub_method("getItemsByID");
    bind_stub_method("getItemsWithPrices");
    bind_stub_method("getLargeFriendAvatar");
    bind_stub_method("getLaunchCommandLine");
    bind_stub_method("getLaunchQueryParam");
    bind_stub_method("getLeaderboardDisplayType");
    bind_stub_method("getLeaderboardEntryCount");
    bind_stub_method("getLeaderboardName");
    bind_stub_method("getLeaderboardSortMethod");
    bind_stub_method("getLinkAtPosition");
    bind_stub_method("getListenSocketAddress");
    bind_stub_method("getLobbyData");
    bind_stub_method("getLobbyGameServer");
    bind_stub_method("getLobbyMemberByIndex");
    bind_stub_method("getLobbyMemberData");
    bind_stub_method("getLobbyMemberLimit");
    bind_stub_method("getLobbyOwner");
    bind_stub_method("getLocalFileChange");
    bind_stub_method("getLocalFileChangeCount");
    bind_stub_method("getLocalPingLocation");
    bind_stub_method("getLocalTimestamp");
    bind_stub_method("getMediumFriendAvatar");
    bind_stub_method("getMostAchievedAchievementInfo");
    bind_stub_method("getMotionData");
    bind_stub_method("getNextMostAchievedAchievementInfo");
    bind_stub_method("getNumAchievements");
    bind_stub_method("getNumActiveBeacons");
    bind_stub_method("getNumBetas");
    bind_stub_method("getNumLobbyMembers");
    bind_stub_method("getNumSubscribedItems");
    bind_stub_method("getNumSupportedGameVersions");
    bind_stub_method("getNumberOfCurrentPlayers");
    bind_stub_method("getOPFSettings");
    bind_stub_method("getOPFStringForApp");
    bind_stub_method("getP2PSessionState");
    bind_stub_method("getPOPCount");
    bind_stub_method("getPOPList");
    bind_stub_method("getPersonaState");
    bind_stub_method("getPingToDataCenter");
    bind_stub_method("getPlaybackStatus");
    bind_stub_method("getPlayerAvatar");
    bind_stub_method("getPlayerNickname");
    bind_stub_method("getPlayerSteamLevel");
    bind_stub_method("getProfileItemPropertyInt");
    bind_stub_method("getProfileItemPropertyString");
    bind_stub_method("getQueryUGCAdditionalPreview");
    bind_stub_method("getQueryUGCChildren");
    bind_stub_method("getQueryUGCContentDescriptors");
    bind_stub_method("getQueryUGCKeyValueTag");
    bind_stub_method("getQueryUGCMetadata");
    bind_stub_method("getQueryUGCNumAdditionalPreviews");
    bind_stub_method("getQueryUGCNumKeyValueTags");
    bind_stub_method("getQueryUGCNumTags");
    bind_stub_method("getQueryUGCPreviewURL");
    bind_stub_method("getQueryUGCResult");
    bind_stub_method("getQueryUGCStatistic");
    bind_stub_method("getQueryUGCTag");
    bind_stub_method("getQueryUGCTagDisplayName");
    bind_stub_method("getQuota");
    bind_stub_method("getRecentPlayers");
    bind_stub_method("getRelayNetworkStatus");
    bind_stub_method("getRemoteFakeIPForConnection");
    bind_stub_method("getRemotePlaySessionID");
    bind_stub_method("getResultItemProperty");
    bind_stub_method("getResultItems");
    bind_stub_method("getResultStatus");
    bind_stub_method("getResultTimestamp");
    bind_stub_method("getSecondsSinceAppActive");
    bind_stub_method("getSecondsSinceComputerActive");
    bind_stub_method("getServerCount");
    bind_stub_method("getServerDetails");
    bind_stub_method("getServerRealTime");
    bind_stub_method("getSessionClientFormFactor");
    bind_stub_method("getSessionClientName");
    bind_stub_method("getSessionClientResolution");
    bind_stub_method("getSessionConnectionInfo");
    bind_stub_method("getSessionCount");
    bind_stub_method("getSessionID");
    bind_stub_method("getSessionInputConfigurationSettings");
    bind_stub_method("getSessionSteamID");
    bind_stub_method("getSmallFriendAvatar");
    bind_stub_method("getStatFloat");
    bind_stub_method("getStatInt");
    bind_stub_method("getSteamID32");
    bind_stub_method("getSteamUILanguage");
    bind_stub_method("getStringForActionOrigin");
    bind_stub_method("getStringForAnalogActionName");
    bind_stub_method("getStringForDigitalActionName");
    bind_stub_method("getStringForXboxOrigin");
    bind_stub_method("getSubscribedItems");
    bind_stub_method("getSupportedGameVersionData");
    bind_stub_method("getSyncPlatforms");
    bind_stub_method("getUGCDetails");
    bind_stub_method("getUGCDownloadProgress");
    bind_stub_method("getUserAchievement");
    bind_stub_method("getUserAchievementAndUnlockTime");
    bind_stub_method("getUserContentDescriptorPreferences");
    bind_stub_method("getUserFriendsGroups");
    bind_stub_method("getUserItemVote");
    bind_stub_method("getUserStatFloat");
    bind_stub_method("getUserStatInt");
    bind_stub_method("getUserSteamFriends");
    bind_stub_method("getUserSteamGroups");
    bind_stub_method("getVideoURL");
    bind_stub_method("getVoice");
    bind_stub_method("getVoiceOptimalSampleRate");
    bind_stub_method("getWorkshopEULAStatus");
    bind_stub_method("get_godotsteam_version");
    bind_stub_method("get_server_list_request");
    bind_stub_method("get_steam_init_result");
    bind_stub_method("goBack");
    bind_stub_method("goForward");
    bind_stub_method("grantPromoItems");
    bind_stub_method("hasEquippedProfileItem");
    bind_stub_method("hasFriend");
    bind_stub_method("hookScreenshots");
    bind_stub_method("hostConfirmGameStart");
    bind_stub_method("htmlInit");
    bind_stub_method("htmlShutdown");
    bind_stub_method("indicateAchievementProgress");
    bind_stub_method("initAuthentication");
    bind_stub_method("initFilterText");
    bind_stub_method("initRelayNetworkAccess");
    bind_stub_method("initWorkshopForGameServer");
    bind_stub_method("initiateGameConnection");
    bind_stub_method("inputInit");
    bind_stub_method("inputShutdown");
    bind_stub_method("installDLC");
    bind_stub_method("inviteUserToGame");
    bind_stub_method("inviteUserToLobby");
    bind_stub_method("isAPICallCompleted");
    bind_stub_method("isAnonAccount");
    bind_stub_method("isAnonUserAccount");
    bind_stub_method("isAppBlocked");
    bind_stub_method("isAppInBlockList");
    bind_stub_method("isAppInstalled");
    bind_stub_method("isBehindNAT");
    bind_stub_method("isBroadcasting");
    bind_stub_method("isChatAccount");
    bind_stub_method("isClanAccount");
    bind_stub_method("isClanChatAdmin");
    bind_stub_method("isClanChatWindowOpenInSteam");
    bind_stub_method("isClanOfficialGameGroup");
    bind_stub_method("isClanPublic");
    bind_stub_method("isCloudEnabledForAccount");
    bind_stub_method("isCloudEnabledForApp");
    bind_stub_method("isConsoleUserAccount");
    bind_stub_method("isCurrentMusicRemote");
    bind_stub_method("isCybercafe");
    bind_stub_method("isDLCInstalled");
    bind_stub_method("isFeatureBlocked");
    bind_stub_method("isFeatureInBlockList");
    bind_stub_method("isFollowing");
    bind_stub_method("isIndividualAccount");
    bind_stub_method("isLobby");
    bind_stub_method("isLowViolence");
    bind_stub_method("isOverlayEnabled");
    bind_stub_method("isParentalLockEnabled");
    bind_stub_method("isParentalLockLocked");
    bind_stub_method("isPhoneIdentifying");
    bind_stub_method("isPhoneRequiringVerification");
    bind_stub_method("isPhoneVerified");
    bind_stub_method("isRefreshing");
    bind_stub_method("isScreenshotsHooked");
    bind_stub_method("isSteamChinaLauncher");
    bind_stub_method("isSteamInBigPictureMode");
    bind_stub_method("isSteamRunningInVR");
    bind_stub_method("isSteamRunningOnSteamDeck");
    bind_stub_method("isSubscribed");
    bind_stub_method("isSubscribedApp");
    bind_stub_method("isSubscribedFromFamilySharing");
    bind_stub_method("isSubscribedFromFreeWeekend");
    bind_stub_method("isTimedTrial");
    bind_stub_method("isTwoFactorEnabled");
    bind_stub_method("isUserInSource");
    bind_stub_method("isVACBanned");
    bind_stub_method("isVRHeadsetStreamingEnabled");
    bind_stub_method("joinClanChatRoom");
    bind_stub_method("joinLobby");
    bind_stub_method("joinParty");
    bind_stub_method("jsDialogResponse");
    bind_stub_method("keyChar");
    bind_stub_method("keyDown");
    bind_stub_method("keyUp");
    bind_stub_method("leaveClanChatRoom");
    bind_stub_method("leaveLobby");
    bind_stub_method("loadItemDefinitions");
    bind_stub_method("loadURL");
    bind_stub_method("markContentCorrupt");
    bind_stub_method("mouseDoubleClick");
    bind_stub_method("mouseDown");
    bind_stub_method("mouseMove");
    bind_stub_method("mouseUp");
    bind_stub_method("mouseWheel");
    bind_stub_method("musicGetVolume");
    bind_stub_method("musicIsEnabled");
    bind_stub_method("musicIsPlaying");
    bind_stub_method("musicPause");
    bind_stub_method("musicPlay");
    bind_stub_method("musicPlayNext");
    bind_stub_method("musicPlayPrev");
    bind_stub_method("musicSetVolume");
    bind_stub_method("newDataAvailable");
    bind_stub_method("onReservationCompleted");
    bind_stub_method("openClanChatWindowInSteam");
    bind_stub_method("openDeveloperTools");
    bind_stub_method("openOverlayToGamePhase");
    bind_stub_method("openOverlayToTimelineEvent");
    bind_stub_method("overlayNeedsPresent");
    bind_stub_method("parsePingLocationString");
    bind_stub_method("pasteFromClipboard");
    bind_stub_method("pingServer");
    bind_stub_method("playerDetails");
    bind_stub_method("playlistDidChange");
    bind_stub_method("playlistWillChange");
    bind_stub_method("prioritizeHTTPRequest");
    bind_stub_method("queueDidChange");
    bind_stub_method("queueWillChange");
    bind_stub_method("readP2PPacket");
    bind_stub_method("receiveMessagesOnChannel");
    bind_stub_method("receiveMessagesOnConnection");
    bind_stub_method("receiveMessagesOnPollGroup");
    bind_stub_method("refreshQuery");
    bind_stub_method("refreshServer");
    bind_stub_method("registerProtocolInOverlayBrowser");
    bind_stub_method("registerSteamMusicRemote");
    bind_stub_method("releaseCookieContainer");
    bind_stub_method("releaseHTTPRequest");
    bind_stub_method("releaseQueryUGCRequest");
    bind_stub_method("releaseRequest");
    bind_stub_method("reload");
    bind_stub_method("removeAppDependency");
    bind_stub_method("removeBrowser");
    bind_stub_method("removeContentDescriptor");
    bind_stub_method("removeDependency");
    bind_stub_method("removeFavoriteGame");
    bind_stub_method("removeItemFromFavorites");
    bind_stub_method("removeItemKeyValueTags");
    bind_stub_method("removeItemPreview");
    bind_stub_method("removeProperty");
    bind_stub_method("removeTimelineEvent");
    bind_stub_method("replyToFriendMessage");
    bind_stub_method("requestClanOfficerList");
    bind_stub_method("requestEligiblePromoItemDefinitionsIDs");
    bind_stub_method("requestEncryptedAppTicket");
    bind_stub_method("requestEquippedProfileItems");
    bind_stub_method("requestFavoritesServerList");
    bind_stub_method("requestFriendRichPresence");
    bind_stub_method("requestFriendsServerList");
    bind_stub_method("requestGlobalAchievementPercentages");
    bind_stub_method("requestGlobalStats");
    bind_stub_method("requestHistoryServerList");
    bind_stub_method("requestInternetServerList");
    bind_stub_method("requestLANServerList");
    bind_stub_method("requestLobbyData");
    bind_stub_method("requestLobbyList");
    bind_stub_method("requestPlayersForGame");
    bind_stub_method("requestPrices");
    bind_stub_method("requestSpectatorServerList");
    bind_stub_method("requestStoreAuthURL");
    bind_stub_method("requestUserInformation");
    bind_stub_method("requestUserStats");
    bind_stub_method("resetAllStats");
    bind_stub_method("resetIdentity");
    bind_stub_method("resetPlaylistEntries");
    bind_stub_method("resetQueueEntries");
    bind_stub_method("restartAppIfNecessary");
    bind_stub_method("retrieveConnectionDetails");
    bind_stub_method("runFrame");
    bind_stub_method("runNetworkingCallbacks");
    bind_stub_method("searchForGameSolo");
    bind_stub_method("searchForGameWithLobby");
    bind_stub_method("sendClanChatMessage");
    bind_stub_method("sendHTTPRequest");
    bind_stub_method("sendHTTPRequestAndStreamResponse");
    bind_stub_method("sendLobbyChatMsg");
    bind_stub_method("sendMessageToConnection");
    bind_stub_method("sendMessageToUser");
    bind_stub_method("sendP2PPacket");
    bind_stub_method("sendQueryUGCRequest");
    bind_stub_method("sendRemotePlayTogetherInvite");
    bind_stub_method("serializeResult");
    bind_stub_method("serverRules");
    bind_stub_method("setAchievement");
    bind_stub_method("setActiveBeta");
    bind_stub_method("setAdminQuery");
    bind_stub_method("setAllowCachedResponse");
    bind_stub_method("setBackgroundMode");
    bind_stub_method("setCertificate");
    bind_stub_method("setCloudEnabledForApp");
    bind_stub_method("setCloudFileNameFilter");
    bind_stub_method("setConnectionConfigValueFloat");
    bind_stub_method("setConnectionConfigValueInt32");
    bind_stub_method("setConnectionConfigValueString");
    bind_stub_method("setConnectionDetails");
    bind_stub_method("setConnectionName");
    bind_stub_method("setConnectionPollGroup");
    bind_stub_method("setCookie");
    bind_stub_method("setCurrentPlaylistEntry");
    bind_stub_method("setCurrentQueueEntry");
    bind_stub_method("setDLCContext");
    bind_stub_method("setDPIScalingFactor");
    bind_stub_method("setDisplayName");
    bind_stub_method("setDualSenseTriggerEffect");
    bind_stub_method("setDurationControlOnlineState");
    bind_stub_method("setGameHostParams");
    bind_stub_method("setGameLauncherMode");
    bind_stub_method("setGamePhaseAttribute");
    bind_stub_method("setGamePhaseID");
    bind_stub_method("setGlobalConfigValueFloat");
    bind_stub_method("setGlobalConfigValueInt32");
    bind_stub_method("setGlobalConfigValueString");
    bind_stub_method("setHTTPCookie");
    bind_stub_method("setHTTPRequestAbsoluteTimeoutMS");
    bind_stub_method("setHTTPRequestContextValue");
    bind_stub_method("setHTTPRequestCookieContainer");
    bind_stub_method("setHTTPRequestGetOrPostParameter");
    bind_stub_method("setHTTPRequestHeaderValue");
    bind_stub_method("setHTTPRequestNetworkActivityTimeout");
    bind_stub_method("setHTTPRequestRawPostBody");
    bind_stub_method("setHTTPRequestRequiresVerifiedCertificate");
    bind_stub_method("setHTTPRequestUserAgentInfo");
    bind_stub_method("setHorizontalScroll");
    bind_stub_method("setInGameVoiceSpeaking");
    bind_stub_method("setInputActionManifestFilePath");
    bind_stub_method("setItemContent");
    bind_stub_method("setItemDescription");
    bind_stub_method("setItemMetadata");
    bind_stub_method("setItemPreview");
    bind_stub_method("setItemTags");
    bind_stub_method("setItemTitle");
    bind_stub_method("setItemUpdateLanguage");
    bind_stub_method("setItemVisibility");
    bind_stub_method("setItemsDisabledLocally");
    bind_stub_method("setKeyFocus");
    bind_stub_method("setLEDColor");
    bind_stub_method("setLanguage");
    bind_stub_method("setListenForFriendsMessages");
    bind_stub_method("setLobbyData");
    bind_stub_method("setLobbyGameServer");
    bind_stub_method("setLobbyJoinable");
    bind_stub_method("setLobbyMemberData");
    bind_stub_method("setLobbyMemberLimit");
    bind_stub_method("setLobbyOwner");
    bind_stub_method("setLobbyType");
    bind_stub_method("setLocation");
    bind_stub_method("setMatchAnyTag");
    bind_stub_method("setMouseCursor");
    bind_stub_method("setMousePosition");
    bind_stub_method("setMouseVisibility");
    bind_stub_method("setOverlayNotificationInset");
    bind_stub_method("setOverlayNotificationPosition");
    bind_stub_method("setPNGIcon64x64");
    bind_stub_method("setPageScaleFactor");
    bind_stub_method("setPlayedWith");
    bind_stub_method("setPlaylistEntry");
    bind_stub_method("setPropertyBool");
    bind_stub_method("setPropertyFloat");
    bind_stub_method("setPropertyInt");
    bind_stub_method("setPropertyString");
    bind_stub_method("setQueueEntry");
    bind_stub_method("setRankedByTrendDays");
    bind_stub_method("setRequiredGameVersions");
    bind_stub_method("setReturnAdditionalPreviews");
    bind_stub_method("setReturnChildren");
    bind_stub_method("setReturnKeyValueTags");
    bind_stub_method("setReturnLongDescription");
    bind_stub_method("setReturnMetadata");
    bind_stub_method("setReturnOnlyIDs");
    bind_stub_method("setReturnPlaytimeStats");
    bind_stub_method("setReturnTotalOnly");
    bind_stub_method("setRichPresence");
    bind_stub_method("setSearchText");
    bind_stub_method("setSize");
    bind_stub_method("setStatFloat");
    bind_stub_method("setStatInt");
    bind_stub_method("setSubscriptionsLoadOrder");
    bind_stub_method("setSyncPlatforms");
    bind_stub_method("setTimeCreatedDateRange");
    bind_stub_method("setTimeUpdatedDateRange");
    bind_stub_method("setTimelineGameMode");
    bind_stub_method("setTimelineTooltip");
    bind_stub_method("setUserItemVote");
    bind_stub_method("setVRHeadsetStreamingEnabled");
    bind_stub_method("setVerticalScroll");
    bind_stub_method("set_server_list_request");
    bind_stub_method("showBindingPanel");
    bind_stub_method("showFloatingGamepadTextInput");
    bind_stub_method("showGamepadTextInput");
    bind_stub_method("showRemotePlayTogetherUI");
    bind_stub_method("showWorkshopEULA");
    bind_stub_method("startGamePhase");
    bind_stub_method("startItemUpdate");
    bind_stub_method("startPlaytimeTracking");
    bind_stub_method("startPurchase");
    bind_stub_method("startRangeTimelineEvent");
    bind_stub_method("startUpdateProperties");
    bind_stub_method("startVRDashboard");
    bind_stub_method("startVoiceRecording");
    bind_stub_method("steamShutdown");
    bind_stub_method("stopAnalogActionMomentum");
    bind_stub_method("stopFind");
    bind_stub_method("stopLoad");
    bind_stub_method("stopPlaytimeTracking");
    bind_stub_method("stopPlaytimeTrackingForAllItems");
    bind_stub_method("stopVoiceRecording");
    bind_stub_method("storeStats");
    bind_stub_method("submitItemUpdate");
    bind_stub_method("submitPlayerResult");
    bind_stub_method("submitUpdateProperties");
    bind_stub_method("subscribeItem");
    bind_stub_method("suspendDownloads");
    bind_stub_method("tagPublishedFile");
    bind_stub_method("tagUser");
    bind_stub_method("terminateGameConnection");
    bind_stub_method("transferItemQuantity");
    bind_stub_method("translateActionOrigin");
    bind_stub_method("triggerHapticPulse");
    bind_stub_method("triggerItemDrop");
    bind_stub_method("triggerRepeatedHapticPulse");
    bind_stub_method("triggerScreenshot");
    bind_stub_method("triggerSimpleHapticEvent");
    bind_stub_method("triggerVibration");
    bind_stub_method("triggerVibrationExtended");
    bind_stub_method("ugcDownload");
    bind_stub_method("ugcDownloadToLocation");
    bind_stub_method("ugcRead");
    bind_stub_method("uninstallDLC");
    bind_stub_method("unsubscribeItem");
    bind_stub_method("updateAvgRateStat");
    bind_stub_method("updateCurrentEntryCoverArt");
    bind_stub_method("updateCurrentEntryElapsedSeconds");
    bind_stub_method("updateCurrentEntryText");
    bind_stub_method("updateItemPreviewFile");
    bind_stub_method("updateItemPreviewVideo");
    bind_stub_method("updateLooped");
    bind_stub_method("updatePlaybackStatus");
    bind_stub_method("updateRangeTimelineEvent");
    bind_stub_method("updateShuffled");
    bind_stub_method("updateVolume");
    bind_stub_method("uploadLeaderboardScore");
    bind_stub_method("userHasLicenseForApp");
    bind_stub_method("viewSource");
    bind_stub_method("waitForData");
    bind_stub_method("writeScreenshot");

    // Constants from GodotSteam (binding with literal values since
    // we don't define C++ enums — game scripts only use these as named ints)
#define BIND_STEAM_CONSTANT(name, val) \
    ClassDB::bind_integer_constant(get_class_static(), StringName(), StringName(#name), val)

    BIND_STEAM_CONSTANT(ACCOUNT_ID_INVALID, 0);
    BIND_STEAM_CONSTANT(API_CALL_INVALID, 0);
    BIND_STEAM_CONSTANT(APP_ID_INVALID, 0);
    BIND_STEAM_CONSTANT(AUTH_TICKET_INVALID, 0);
    BIND_STEAM_CONSTANT(DEPOT_ID_INVALID, 0);
    BIND_STEAM_CONSTANT(GAME_EXTRA_INFO_MAX, 64);
    BIND_STEAM_CONSTANT(INVALID_BREAKPAD_HANDLE, 0);
    BIND_STEAM_CONSTANT(QUERY_PORT_ERROR, 65534);
    BIND_STEAM_CONSTANT(QUERY_PORT_NOT_INITIALIZED, 65535);
    BIND_STEAM_CONSTANT(STEAM_ACCOUNT_ID_MASK, 4294967295);
    BIND_STEAM_CONSTANT(STEAM_ACCOUNT_INSTANCE_MASK, 1048575);
    BIND_STEAM_CONSTANT(STEAM_BUFFER_SIZE, 255);
    BIND_STEAM_CONSTANT(STEAM_LARGE_BUFFER_SIZE, 8160);
    BIND_STEAM_CONSTANT(STEAM_MAX_ERROR_MESSAGE, 1024);
    BIND_STEAM_CONSTANT(STEAM_USER_CONSOLE_INSTANCE, 2);
    BIND_STEAM_CONSTANT(STEAM_USER_DESKTOP_INSTANCE, 1);
    BIND_STEAM_CONSTANT(STEAM_USER_WEB_INSTANCE, 4);
    BIND_STEAM_CONSTANT(CHAT_METADATA_MAX, 8192);
    BIND_STEAM_CONSTANT(ENUMERATED_FOLLOWERS_MAX, 50);
    BIND_STEAM_CONSTANT(FRIEND_GAME_INFO_QUERY_PORT_ERROR, 65534);
    BIND_STEAM_CONSTANT(FRIEND_GAME_INFO_QUERY_PORT_NOT_INITIALIZED, 65535);
    BIND_STEAM_CONSTANT(FRIENDS_GROUP_LIMIT, 100);
    BIND_STEAM_CONSTANT(INVALID_FRIEND_GROUP_ID, -1);
    BIND_STEAM_CONSTANT(MAX_FRIENDS_GROUP_NAME, 64);
    BIND_STEAM_CONSTANT(MAX_RICH_PRESENCE_KEY_LENGTH, 64);
    BIND_STEAM_CONSTANT(MAX_RICH_PRESENCE_KEYS, 30);
    BIND_STEAM_CONSTANT(MAX_RICH_PRESENCE_VALUE_LENTH, 256);
    BIND_STEAM_CONSTANT(PERSONA_NAME_MAX_UTF8, 128);
    BIND_STEAM_CONSTANT(PERSONA_NAME_MAX_UTF16, 32);
    BIND_STEAM_CONSTANT(INVALID_HTMLBROWSER, 0);
    BIND_STEAM_CONSTANT(HTTPCOOKIE_INVALID_HANDLE, 0);
    BIND_STEAM_CONSTANT(HTTPREQUEST_INVALID_HANDLE, 0);
    BIND_STEAM_CONSTANT(INPUT_HANDLE_ALL_CONTROLLERS, -1);
    BIND_STEAM_CONSTANT(INPUT_MAX_ACTIVE_LAYERS, 16);
    BIND_STEAM_CONSTANT(INPUT_MAX_ANALOG_ACTIONS, 24);
    BIND_STEAM_CONSTANT(INPUT_MAX_ANALOG_ACTION_DATA, 1);
    BIND_STEAM_CONSTANT(INPUT_MAX_COUNT, 16);
    BIND_STEAM_CONSTANT(INPUT_MAX_DIGITAL_ACTIONS, 256);
    BIND_STEAM_CONSTANT(INPUT_MAX_ORIGINS, 8);
    BIND_STEAM_CONSTANT(INPUT_MIN_ANALOG_ACTION_DATA, -1);
    BIND_STEAM_CONSTANT(INVENTORY_RESULT_INVALID, -1);
    BIND_STEAM_CONSTANT(ITEM_INSTANCE_ID_INVALID, -1);
    BIND_STEAM_CONSTANT(FAVORITE_FLAG_FAVORITE, 1);
    BIND_STEAM_CONSTANT(FAVORITE_FLAG_HISTORY, 2);
    BIND_STEAM_CONSTANT(FAVORITE_FLAG_NONE, 0);
    BIND_STEAM_CONSTANT(MAX_LOBBY_KEY_LENGTH, 255);
    BIND_STEAM_CONSTANT(SERVER_QUERY_INVALID, -1);
    BIND_STEAM_CONSTANT(MAX_GAME_SERVER_GAME_DATA, 2048);
    BIND_STEAM_CONSTANT(MAX_GAME_SERVER_GAME_DESCRIPTION, 64);
    BIND_STEAM_CONSTANT(MAX_GAME_SERVER_GAME_DIR, 32);
    BIND_STEAM_CONSTANT(MAX_GAME_SERVER_MAP_NAME, 32);
    BIND_STEAM_CONSTANT(MAX_GAME_SERVER_NAME, 64);
    BIND_STEAM_CONSTANT(MAX_GAME_SERVER_TAGS, 128);
    BIND_STEAM_CONSTANT(MUSIC_NAME_MAX_LENGTH, 255);
    BIND_STEAM_CONSTANT(MUSIC_PNG_MAX_LENGTH, 65535);
    BIND_STEAM_CONSTANT(MAX_STEAM_PACKET_SIZE, 524288);
    BIND_STEAM_CONSTANT(LISTEN_SOCKET_INVALID, 0);
    BIND_STEAM_CONSTANT(MAX_NETWORKING_ERROR_MESSAGE, 1024);
    BIND_STEAM_CONSTANT(MAX_NETWORKING_PING_LOCATION_STRING, 1024);
    BIND_STEAM_CONSTANT(NETWORKING_CONFIG_P2P_TRANSPORT_ICE_DEFAULT, -1);
    BIND_STEAM_CONSTANT(NETWORKING_CONFIG_P2P_TRANSPORT_ICE_DISABLE, 0);
    BIND_STEAM_CONSTANT(NETWORKING_CONFIG_P2P_TRANSPORT_ICE_RELAY, 1);
    BIND_STEAM_CONSTANT(NETWORKING_CONFIG_P2P_TRANSPORT_ICE_PRIVATE, 2);
    BIND_STEAM_CONSTANT(NETWORKING_CONFIG_P2P_TRANSPORT_ICE_PUBLIC, 4);
    BIND_STEAM_CONSTANT(NETWORKING_CONFIG_P2P_TRANSPORT_ICE_ALL, 2147483647);
    BIND_STEAM_CONSTANT(NETWORKING_CONNECTION_INFO_FLAG_UNAUTHENTICATED, 1);
    BIND_STEAM_CONSTANT(NETWORKING_CONNECTION_INFO_FLAG_UNENCRYPTED, 2);
    BIND_STEAM_CONSTANT(NETWORKING_CONNECTION_INFO_FLAG_LOOPBACK_BUFFERS, 4);
    BIND_STEAM_CONSTANT(NETWORKING_CONNECTION_INFO_FLAG_FAST, 8);
    BIND_STEAM_CONSTANT(NETWORKING_CONNECTION_INFO_FLAG_RELAYED, 16);
    BIND_STEAM_CONSTANT(NETWORKING_CONNECTION_INFO_FLAG_DUALWIFI, 32);
    BIND_STEAM_CONSTANT(NETWORKING_CONNECTION_INVALID, 0);
    BIND_STEAM_CONSTANT(NETWORKING_MAX_CONNECTION_APP_NAME, 32);
    BIND_STEAM_CONSTANT(NETWORKING_MAX_CONNECTION_CLOSE_REASON, 128);
    BIND_STEAM_CONSTANT(NETWORKING_MAX_CONNECTION_DESCRIPTION, 128);
    BIND_STEAM_CONSTANT(NETWORKING_PING_FAILED, -1);
    BIND_STEAM_CONSTANT(NETWORKING_PING_UNKNOWN, -2);
    BIND_STEAM_CONSTANT(NETWORKING_SEND_UNRELIABLE, 0);
    BIND_STEAM_CONSTANT(NETWORKING_SEND_NO_NAGLE, 1);
    BIND_STEAM_CONSTANT(NETWORKING_SEND_URELIABLE_NO_NAGLE, 1);
    BIND_STEAM_CONSTANT(NETWORKING_SEND_NO_DELAY, 4);
    BIND_STEAM_CONSTANT(NETWORKING_SEND_UNRELIABLE_NO_DELAY, 5);
    BIND_STEAM_CONSTANT(NETWORKING_SEND_RELIABLE, 8);
    BIND_STEAM_CONSTANT(NETWORKING_SEND_RELIABLE_NO_NAGLE, 9);
    BIND_STEAM_CONSTANT(NETWORKING_SEND_USE_CURRENT_THREAD, 16);
    BIND_STEAM_CONSTANT(NETWORKING_SEND_AUTORESTART_BROKEN_SESSION, 32);
    BIND_STEAM_CONSTANT(ENUMERATE_PUBLISHED_FILES_MAX_RESULTS, 50);
    BIND_STEAM_CONSTANT(FILE_NAME_MAX, 260);
    BIND_STEAM_CONSTANT(MAX_CLOUD_FILE_CHUNK_SIZE, 104857600);
    BIND_STEAM_CONSTANT(PUBLISHED_DOCUMENT_CHANGE_DESCRIPTION_MAX, 8000);
    BIND_STEAM_CONSTANT(PUBLISHED_DOCUMENT_DESCRIPTION_MAX, 8000);
    BIND_STEAM_CONSTANT(PUBLISHED_DOCUMENT_TITLE_MAX, 129);
    BIND_STEAM_CONSTANT(PUBLISHED_FILE_ID_INVALID, 0);
    BIND_STEAM_CONSTANT(PUBLISHED_FILE_UPDATE_HANDLE_INVALID, -1);
    BIND_STEAM_CONSTANT(PUBLISHED_FILE_URL_MAX, 256);
    BIND_STEAM_CONSTANT(TAG_LIST_MAX, 1025);
    BIND_STEAM_CONSTANT(UGC_FILE_STREAM_HANDLE_INVALID, -1);
    BIND_STEAM_CONSTANT(UGC_HANDLE_INVALID, -1);
    BIND_STEAM_CONSTANT(MAX_TAGGED_PUBLISHED_FILES, 32);
    BIND_STEAM_CONSTANT(MAX_TAGGED_USERS, 32);
    BIND_STEAM_CONSTANT(SCREENSHOT_INVALID_HANDLE, 0);
    BIND_STEAM_CONSTANT(SCREENSHOT_THUMB_WIDTH, 200);
    BIND_STEAM_CONSTANT(UFS_TAG_TYPE_MAX, 255);
    BIND_STEAM_CONSTANT(UFS_TAG_VALUE_MAX, 255);
    BIND_STEAM_CONSTANT(DEVELOPER_METADATA_MAX, 5000);
    BIND_STEAM_CONSTANT(NUM_UGC_RESULTS_PER_PAGE, 50);
    BIND_STEAM_CONSTANT(UGC_QUERY_HANDLE_INVALID, -1);
    BIND_STEAM_CONSTANT(UGC_UPDATE_HANDLE_INVALID, -1);
    BIND_STEAM_CONSTANT(LEADERBOARD_DETAIL_MAX, 64);
    BIND_STEAM_CONSTANT(LEADERBOARD_NAME_MAX, 128);
    BIND_STEAM_CONSTANT(STAT_NAME_MAX, 128);
    BIND_STEAM_CONSTANT(ACCOUNT_TYPE_INVALID, 0);
    BIND_STEAM_CONSTANT(ACCOUNT_TYPE_INDIVIDUAL, 1);
    BIND_STEAM_CONSTANT(ACCOUNT_TYPE_MULTISEAT, 2);
    BIND_STEAM_CONSTANT(ACCOUNT_TYPE_GAME_SERVER, 3);
    BIND_STEAM_CONSTANT(ACCOUNT_TYPE_ANON_GAME_SERVER, 4);
    BIND_STEAM_CONSTANT(ACCOUNT_TYPE_PENDING, 5);
    BIND_STEAM_CONSTANT(ACCOUNT_TYPE_CONTENT_SERVER, 6);
    BIND_STEAM_CONSTANT(ACCOUNT_TYPE_CLAN, 7);
    BIND_STEAM_CONSTANT(ACCOUNT_TYPE_CHAT, 8);
    BIND_STEAM_CONSTANT(ACCOUNT_TYPE_CONSOLE_USER, 9);
    BIND_STEAM_CONSTANT(ACCOUNT_TYPE_ANON_USER, 10);
    BIND_STEAM_CONSTANT(ACCOUNT_TYPE_MAX, 11);
    BIND_STEAM_CONSTANT(STEAM_API_CALL_FAILURE_NONE, -1);
    BIND_STEAM_CONSTANT(STEAM_API_CALL_FAILURE_STEAM_GONE, 0);
    BIND_STEAM_CONSTANT(STEAM_API_CALL_FAILURE_NETWORK_FAILURE, 1);
    BIND_STEAM_CONSTANT(STEAM_API_CALL_FAILURE_INVALID_HANDLE, 2);
    BIND_STEAM_CONSTANT(STEAM_API_CALL_FAILURE_MISMATCHED_CALLBACK, 3);
    BIND_STEAM_CONSTANT(AUDIO_PLAYBACK_UNDEFINED, 0);
    BIND_STEAM_CONSTANT(AUDIO_PLAYBACK_PLAYING, 1);
    BIND_STEAM_CONSTANT(AUDIO_PLAYBACK_PAUSED, 2);
    BIND_STEAM_CONSTANT(AUDIO_PLAYBACK_IDLE, 3);
    BIND_STEAM_CONSTANT(AUTH_SESSION_RESPONSE_OK, 0);
    BIND_STEAM_CONSTANT(AUTH_SESSION_RESPONSE_USER_NOT_CONNECTED_TO_STEAM, 1);
    BIND_STEAM_CONSTANT(AUTH_SESSION_RESPONSE_NO_LICENSE_OR_EXPIRED, 2);
    BIND_STEAM_CONSTANT(AUTH_SESSION_RESPONSE_VAC_BANNED, 3);
    BIND_STEAM_CONSTANT(AUTH_SESSION_RESPONSE_LOGGED_IN_ELSEWHERE, 4);
    BIND_STEAM_CONSTANT(AUTH_SESSION_RESPONSE_VAC_CHECK_TIMED_OUT, 5);
    BIND_STEAM_CONSTANT(AUTH_SESSION_RESPONSE_AUTH_TICKET_CANCELED, 6);
    BIND_STEAM_CONSTANT(AUTH_SESSION_RESPONSE_AUTH_TICKET_INVALID_ALREADY_USED, 7);
    BIND_STEAM_CONSTANT(AUTH_SESSION_RESPONSE_AUTH_TICKET_INVALID, 8);
    BIND_STEAM_CONSTANT(AUTH_SESSION_RESPONSE_PUBLISHER_ISSUED_BAN, 9);
    BIND_STEAM_CONSTANT(AUTH_SESSION_RESPONSE_AUTH_TICKET_NETWORK_IDENTITY_FAILURE, 10);
    BIND_STEAM_CONSTANT(AVATAR_SMALL, 1);
    BIND_STEAM_CONSTANT(AVATAR_MEDIUM, 2);
    BIND_STEAM_CONSTANT(AVATAR_LARGE, 3);
    BIND_STEAM_CONSTANT(BEGIN_AUTH_SESSION_RESULT_OK, 0);
    BIND_STEAM_CONSTANT(BEGIN_AUTH_SESSION_RESULT_INVALID_TICKET, 1);
    BIND_STEAM_CONSTANT(BEGIN_AUTH_SESSION_RESULT_DUPLICATE_REQUEST, 2);
    BIND_STEAM_CONSTANT(BEGIN_AUTH_SESSION_RESULT_INVALID_VERSION, 3);
    BIND_STEAM_CONSTANT(BEGIN_AUTH_SESSION_RESULT_GAME_MISMATCH, 4);
    BIND_STEAM_CONSTANT(BEGIN_AUTH_SESSION_RESULT_EXPIRED_TICKET, 5);
    BIND_STEAM_CONSTANT(BETA_BRANCH_NONE, 0);
    BIND_STEAM_CONSTANT(BETA_BRANCH_DEFAULT, 1);
    BIND_STEAM_CONSTANT(BETA_BRANCH_AVAILABLE, 2);
    BIND_STEAM_CONSTANT(BETA_BRANCH_PRIVATE, 4);
    BIND_STEAM_CONSTANT(BETA_BRANCH_SELECTED, 8);
    BIND_STEAM_CONSTANT(BETA_BRANCH_INSTALLED, 16);
    BIND_STEAM_CONSTANT(BROADCAST_UPLOAD_RESULT_NONE, 0);
    BIND_STEAM_CONSTANT(BROADCAST_UPLOAD_RESULT_OK, 1);
    BIND_STEAM_CONSTANT(BROADCAST_UPLOAD_RESULT_INIT_FAILED, 2);
    BIND_STEAM_CONSTANT(BROADCAST_UPLOAD_RESULT_FRAME_FAILED, 3);
    BIND_STEAM_CONSTANT(BROADCAST_UPLOAD_RESULT_TIME_OUT, 4);
    BIND_STEAM_CONSTANT(BROADCAST_UPLOAD_RESULT_BANDWIDTH_EXCEEDED, 5);
    BIND_STEAM_CONSTANT(BROADCAST_UPLOAD_RESULT_LOW_FPS, 6);
    BIND_STEAM_CONSTANT(BROADCAST_UPLOAD_RESULT_MISSING_KEYFRAMES, 7);
    BIND_STEAM_CONSTANT(BROADCAST_UPLOAD_RESULT_NO_CONNECTION, 8);
    BIND_STEAM_CONSTANT(BROADCAST_UPLOAD_RESULT_RELAY_FAILED, 9);
    BIND_STEAM_CONSTANT(BROADCAST_UPLOAD_RESULT_SETTINGS_CHANGED, 10);
    BIND_STEAM_CONSTANT(BROADCAST_UPLOAD_RESULT_MISSING_AUDIO, 11);
    BIND_STEAM_CONSTANT(BROADCAST_UPLOAD_RESULT_TOO_FAR_BEHIND, 12);
    BIND_STEAM_CONSTANT(BROADCAST_UPLOAD_RESULT_TRANSCODE_BEHIND, 13);
    BIND_STEAM_CONSTANT(BROADCAST_UPLOAD_RESULT_NOT_ALLOWED_TO_PLAY, 14);
    BIND_STEAM_CONSTANT(BROADCAST_UPLOAD_RESULT_BUSY, 15);
    BIND_STEAM_CONSTANT(BROADCAST_UPLOAD_RESULT_BANNED, 16);
    BIND_STEAM_CONSTANT(BROADCAST_UPLOAD_RESULT_ALREADY_ACTIVE, 17);
    BIND_STEAM_CONSTANT(BROADCAST_UPLOAD_RESULT_FORCED_OFF, 18);
    BIND_STEAM_CONSTANT(BROADCAST_UPLOAD_RESULT_AUDIO_BEHIND, 19);
    BIND_STEAM_CONSTANT(BROADCAST_UPLOAD_RESULT_SHUTDOWN, 20);
    BIND_STEAM_CONSTANT(BROADCAST_UPLOAD_RESULT_DISCONNECT, 21);
    BIND_STEAM_CONSTANT(BROADCAST_UPLOAD_RESULT_VIDEO_INIT_FAILED, 22);
    BIND_STEAM_CONSTANT(BROADCAST_UPLOAD_RESULT_AUDIO_INIT_FAILED, 23);
    BIND_STEAM_CONSTANT(CHAT_ENTRY_TYPE_INVALID, 0);
    BIND_STEAM_CONSTANT(CHAT_ENTRY_TYPE_CHAT_MSG, 1);

#undef BIND_STEAM_CONSTANT
}
